name: LazyCat Build
on:
  pull_request:
    branches:
      - meow
  push:
    branches:
      - meow
    tags:
      - "*"

env:
  HASHLINK: "hashlink-7aa39e591b6f0d312d27f323179e8b60abb9fb01"
  HASHLINK_URL: "https://github.com/HaxeFoundation/hashlink/archive/7aa39e591b6f0d312d27f323179e8b60abb9fb01.tar.gz"
  HASHLINK_BREW_DEPS: "cmake jpeg-turbo libpng sdl2 libogg libvorbis openal-soft mbedtls@2 libuv openssl gnu-tar coreutils"
  HASHLINK_APT_DEPS: "libpng-dev libturbojpeg-dev libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev"

jobs:
  compile-hashlink:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.3.1"
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install ${{ env.HASHLINK_APT_DEPS }}
      - name: Install Mac dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install ${{ env.HASHLINK_BREW_DEPS }}
          brew link mbedtls@2
      - name: Cache hashlink
        id: cache-hashlink
        uses: actions/cache@v3
        with:
          path: ${{ env.HASHLINK }}
          key: ${{ runner.os }}-${{ env.HASHLINK }}
      - name: Build hashlink
        if: steps.cache-hashlink.outputs.cache-hit != 'true'
        run: |
          curl -L ${{ env.HASHLINK_URL }} | tar -xz
          cd ${{ env.HASHLINK }}
          make

  build-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.3.1"
      - name: Build
        run: make export/js
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: lazycat
          path: export/js/lazycat-*.tar.gz

  build-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.3.1"
      - name: Build
        run: make export/source
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: lazycat
          path: export/source/lazycat-*.tar.gz

  build-hl:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    needs: compile-hashlink
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.3.1"
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install ${{ env.HASHLINK_APT_DEPS }}
      - name: Install Mac dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install ${{ env.HASHLINK_BREW_DEPS }}
          brew link mbedtls@2
      - name: Cache hashlink
        id: cache-hashlink
        uses: actions/cache@v3
        with:
          path: ${{ env.HASHLINK }}
          key: ${{ runner.os }}-${{ env.HASHLINK }}
      - name: Build
        run: make export/hl
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: lazycat
          path: export/hl/lazycat-*.tar.gz

  build-native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    needs: compile-hashlink
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.3.1"
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install ${{ env.HASHLINK_APT_DEPS }}
      - name: Install Mac dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install ${{ env.HASHLINK_BREW_DEPS }}
          brew link mbedtls@2
      - name: Cache hashlink
        id: cache-hashlink
        uses: actions/cache@v3
        with:
          path: ${{ env.HASHLINK }}
          key: ${{ runner.os }}-${{ env.HASHLINK }}
      - name: Build
        run: make export/native
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: lazycat
          path: export/native/lazycat-*.tar.gz

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.3.1"
      - name: Lint
        run: make lint
