name: Build LazyCat
on:
  pull_request:
    branches:
      - meow
  push:
    branches:
      - meow
  schedule:
    - cron: '04 07 * * *'

jobs:
  build-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.1.4"
      - name: Build
        run: make export/js
  build-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.1.4"
      - name: Build
        run: make export/source
  build-hl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.1.4"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libpng-dev libturbojpeg-dev libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev
      - name: Build hashlink
        run: |
          wget https://github.com/HaxeFoundation/hashlink/archive/1.11.tar.gz
          tar xf 1.11.tar.gz
          cd hashlink-1.11
          make
          sudo make install
      - name: Build
        run: make export/hl
  build-native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.1.4"
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libpng-dev libturbojpeg-dev libvorbis-dev libopenal-dev libsdl2-dev libmbedtls-dev libuv1-dev
      - name: Install Mac dependencies
        if: matrix.os == 'macos-latest'
        run: brew install cmake jpeg-turbo libpng sdl2 libogg libvorbis openal-soft mbedtls libuv openssl
      - name: Build hashlink
        run: |
          wget https://github.com/HaxeFoundation/hashlink/archive/1.11.tar.gz
          tar xf 1.11.tar.gz
          cd hashlink-1.11
          make
          sudo make install
      - name: Build
        run: make export/native
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.1.4"
      - name: Lint
        run: make lint
